// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactTimeago = require("react-timeago");

function make(date, children) {
  return ReasonReact.wrapJsForReason(ReactTimeago.default, {
              date: date
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
