// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Config = require("../Config.js");
var Helmet = require("../bindings/gatsby/helmet.js");
var Vrroom = require("vrroom/src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PackageSummary = require("./PackageSummary.js");

var component = ReasonReact.statelessComponent("CollectionPage");

function make(title, packages, param) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Helmet.make(Config.titleTemplate(title), undefined, undefined, undefined, /* array */[])), React.createElement("h1", undefined, Vrroom.text(title + (" (" + (String(packages.length) + ")")))), ReasonReact.element(undefined, undefined, Curry._3(Vrroom.Control[/* Map */0][/* make */1], packages, undefined, (function ($$package) {
                                    return ReasonReact.element($$package.id, undefined, PackageSummary.make($$package, /* array */[]));
                                  }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
