// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("../styles/Theme.js");
var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");

var root = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* :: */[
        TypedGlamor.justifyContent(TypedGlamor.spaceBetween),
        /* :: */[
          TypedGlamor.marginBottom(TypedGlamor.em(0.5)),
          /* [] */0
        ]
      ]
    ]);

var name = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.textDecoration(TypedGlamor.none),
      /* :: */[
        TypedGlamor.hover(/* :: */[
              TypedGlamor.textDecoration(TypedGlamor.underline),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var version = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.fontSize(TypedGlamor.em(0.85)),
      /* :: */[
        TypedGlamor.fontStyle(TypedGlamor.italic),
        /* :: */[
          TypedGlamor.marginLeft(TypedGlamor.em(0.5)),
          /* :: */[
            TypedGlamor.opacity(0.5),
            /* [] */0
          ]
        ]
      ]
    ]);

var updated = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.opacity(0.5),
      /* :: */[
        TypedGlamor.fontSize(TypedGlamor.em(0.85)),
        /* :: */[
          TypedGlamor.whiteSpace(TypedGlamor.nowrap),
          /* :: */[
            TypedGlamor.opacity(0.75),
            /* [] */0
          ]
        ]
      ]
    ]);

var stars = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.opacity(0.5),
      /* :: */[
        TypedGlamor.fontSize(TypedGlamor.em(0.85)),
        /* :: */[
          TypedGlamor.whiteSpace(TypedGlamor.nowrap),
          /* :: */[
            TypedGlamor.opacity(0.75),
            /* [] */0
          ]
        ]
      ]
    ]);

var starIcon = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.marginLeft(TypedGlamor.em(0.25)),
      /* :: */[
        TypedGlamor.transforms(/* :: */[
              TypedGlamor.translateY(TypedGlamor.px(-1)),
              /* [] */0
            ]),
        /* :: */[
          TypedGlamor.unsafe("fill", Theme.Inverted[/* Color */0][/* text */1]),
          /* :: */[
            TypedGlamor.opacity(0.5),
            /* [] */0
          ]
        ]
      ]
    ]);

exports.root = root;
exports.name = name;
exports.version = version;
exports.updated = updated;
exports.stars = stars;
exports.starIcon = starIcon;
/* root Not a pure module */
