// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function getNodes(result) {
  return $$Array.map((function (edge) {
                return edge.node;
              }), result.edges);
}

exports.getNodes = getNodes;
/* No side effect */
