// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Search = /* module */[
  /* appId */"NSSP00E9NN",
  /* apiKey */"865b2e3bf9dc5bc41e5456eb49b9a471",
  /* packageIndex */"rholang-packages"
];

function titleTemplate(title) {
  return "" + (String(title) + " | redex");
}

exports.Search = Search;
exports.titleTemplate = titleTemplate;
/* No side effect */
