// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Footer = require("../components/Footer.js");
var Helmet = require("../bindings/gatsby/helmet.js");
var SearchBox = require("../components/SearchBox.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var CommonStyles = require("../styles/CommonStyles.js");
var IndexLayoutStyles = require("./IndexLayoutStyles.js");

var component = ReasonReact.statelessComponent("PageLayout");

function make(children, param) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: TypedGlamor.toString(IndexLayoutStyles.root)
                        }, ReasonReact.element(undefined, undefined, Helmet.make(undefined, undefined, "redex", undefined, /* array */[
                                  React.createElement("html", {
                                        lang: "en"
                                      }),
                                  React.createElement("meta", {
                                        content: "Package index for the ReasonML/BuckleScript ecosystem",
                                        name: "description"
                                      })
                                ])), React.createElement("div", {
                              className: TypedGlamor.toString(IndexLayoutStyles.header)
                            }, React.createElement("div", {
                                  className: TypedGlamor.toString(CommonStyles.widthContainer)
                                }, ReasonReact.element(undefined, undefined, SearchBox.make(undefined, /* array */[])))), React.createElement("div", {
                              className: TypedGlamor.toString(CommonStyles.widthContainer)
                            }, children), ReasonReact.element(undefined, undefined, Footer.make(/* Index */-784200974, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children, /* array */[]);
      }));

var Styles = 0;

var $$__esModule = true;

exports.Styles = Styles;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.$$__esModule = $$__esModule;
/* component Not a pure module */
